### PR TITLE
makes copy of original configuration and use original callbacks

### PR DESCRIPTION
**Pull request by shadybones**
so that a global configuration object can be used
related to #111

### CODE REVIEW

**Comment by outsideris** [comment]
I understand what you intend in this PR (#111).
I feel it is too complex, and it is not efficient both callbacks, an original callback and a callback from attributes, are invoked in every callback.
So, I fixed such as <https://gist.github.com/outsideris/4045c5912d116511d3b2>. How do you think about that?
I wanted it use basically callbacks in summernote config object and overwrite it if a user specifies callback in an attribute.

**Comment by shadybones** [comment]
That would work, as long as you still make a copy of the original config object (I can't see it in the gist you made):
```
var currentElement, summernoteConfig = angular.copy($scope.summernoteConfig) || {};
```

**Comment by outsideris** [comment]
@shadybones I make the diff in gist on top of your commit so, I ommit the making a copy parts.
If you agreed with the diff, please update your PR. After that I will merge it.
Let me know if you are busy. I will modify it after I merge your current PR.

**Comment by shadybones** [comment]
@outsideris  I'm wondering, was there a reason onChange was done differently than the rest of the callbacks? I've implemented your changes into the PR.

**Comment by outsideris** [comment]
Thank you.
onChange is defferent because it have to sync with ngModel.

**Pull request merged**
